### ISSUE TITLE
[ENH] - Add option to customize .condarc  default environment paths in jupyterhub_config.py

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari-slurm#147]
### Feature description

Currently, when users create an environment using conda-store, it is not automatically available for use in both the Terminal and Jupyter Notebook. This creates inconvenience and inefficiency as users have to manually configure their environments for each use case. 

We need to ensure that newly created environments are automatically accessible for users in both ecosystems when they spin up a new lab server.

For reference, a similar functionality is implemented in Nebari (linked below). However, conveniently conda-store group environments seems to be already present on the user terminal so changes on this regard doesn't seem to be required (e.g catching the ` groups` object as in the Nebari's implementation )

Reference:
[Nebari Environment Setup](https://github.com/nebari-dev/nebari/blob/5463e8df9e8d53a266a7b9d3d4e27353ec43c40b/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/jupyterhub/files/jupyterhub/03-profiles.py#L347)

Current Configuration Example:
```json
{
  "envs_dirs": [
    "/opt/conda-store/conda-store/{username}/envs"
  ],
  "changeps1": true
}
``` 

### Value and/or benefit

Users will be able to access and experiment with their conda-store environments.

**Comment by aktech** [comment]
Merged in #148
